######################################################################
# Automatically generated by qmake (2.01a) vie feb 6 11:30:51 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.moc
SOURCES += main.cpp
