#!/usr/bin/env bash

# This file is part of the Ideal Library
# Copyright (C) 2009 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

testsToSkip="fileTest2 guiTest guiTest2 idleTest nonBlockingGUI timerTest"
skipTest=false

ls build &> /dev/null
if [ $? -ne 0 ]; then
    echo "Please, compile and install project first:"
    echo -e "\t./waf configure --prefix=/some/dir"
    echo -e "\t./waf build [-p]"
    echo -e "\t[sudo] ./waf install"
    exit 1
fi

which valgrind &> /dev/null
if [ $? -ne 0 ]; then
    echo "Valgrind has not been found. Please, install it and retry"
    exit 1
fi

if [ $# -eq 1 ]; then
    testList=$1
elif [ $# -gt 1 ]; then
    echo "usage: ./runIntegrationTests [\"testFoo testBar testFooBar\"]"
    exit 1
else
    testList=$( ls -1 build/default )
fi

for expression in $testList; do
    ls build/default/$expression &> /dev/null
    if [ $? -ne 0 ]; then
        printf "\033[1;37m%s\033[0m - \033[1;31m%s\033[0m\n" $expression "skipping (does not exist)"
        echo
        continue
    fi
    for test in $( ls -d1 build/default/$expression | cut -d/ -f3 ); do
        if [ $test == "wscript" ]; then
            continue
        fi
        for testToSkip in $testsToSkip; do
            if [ $testToSkip == $test ]; then
                skipTest=true
                break
            fi
        done
        if [ $skipTest == true ]; then
            printf "\033[1;37m%s\033[0m - \033[1;33m%s\033[0m\n" $test "skipping (in skip list)"
            echo
            skipTest=false
            continue
        fi
        printf "\033[1;37m%s\033[0m - \033[1;32m%s\033[0m\n" $test "running"
        echo
        echo -e "\t1.- Memcheck results:"
        valgrind build/default/$test/$test 2>&1 | egrep 'ERROR|malloc\/free' | cut -d' ' -f2- | sed "s/^/\t\t/"
        echo -e "\t2.- Helgrind results:"
        valgrind --tool=helgrind build/default/$test/$test 2>&1 | egrep ERROR | cut -d' ' -f2- | sed "s/^/\t\t/"
        echo
    done
done
exit 0
