######################################################################
# Automatically generated by qmake (2.01a) lun dic 29 15:46:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.moc
SOURCES += main.cpp
