######################################################################
# Automatically generated by qmake (2.01a) jue feb 12 23:38:16 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
